### ISSUE TITLE
Is the doc site ready to be published?

### ISSUE THREAD

**Issue by hargasinski** [hargasinski/async#10]
Aside from a logo, the two major milestones (a persistent header, #6, and searching, #2) have been implemented into the site.

Is there anything else that needs to be added before this can be published?

Docs: http://hargasinski.github.io/async/docs.html

/cc @megawac @aearly

**Comment by megawac** [comment]
Make a pull request :) (please exclude the docs/ folder)

On Tue, Jun 28, 2016 at 3:21 AM, Hubert Argasinski <notifications@github.com

**Comment by megawac** [comment]
Also search isn't working on the site as it links to the wrong page (it loses track of route).

**Comment by hargasinski** [comment]
Good thing you noticed that, I tested it locally, so that wasn't a problem. I'll fix that and open the pull request tonight.

**Comment by megawac** [comment]
Sounds good, mind also squashing both of our commits into relevant parts before submitting the PR. Just remove the tweak commits and the ones for rebuilding docs. I'd say 10-20 commits is reasonable for this

**Comment by aearly** [comment]
Thanks for all your hard work @hargasinski .  Anything else you'd like to finish before the final PR?  After the PR, any other tweaks you want to make will have to go through PRs to the upstream project.

**Comment by hargasinski** [comment]
I'm glad to help out. I use async a lot, so I'm glad to finally have a docs site for it. I think everything's good for the PR now, I'll just need to fix the issue @megawac pointed out. Idk if I'll be able to address your comments in #4 without delaying this significantly. Adding the minami theme to the repo will be easy, but it might be difficult to do everything the [jsdoc-fix-html.js](https://github.com/hargasinski/async/blob/docs-jsdocs/support/jsdoc/jsdoc-fix-html.js) script is doing without spending a lot of time modifying the theme. I could slowly work on that in the next couple weeks.

**Comment by aearly** [comment]
I have a feeling `jsdoc-fix-html.js` will stick around for the things we can't accomplish through the template or plugins, totally fine.

**Comment by hargasinski** [comment]
There might be small things that are pointed out when the site goes live, but it should't anything too major. It should be easy to apply those fixes through a PR.

**Comment by hargasinski** [comment]
Oh okay, so yeah, I'll just apply the fix tonight, squash the commits so that they are more relevant, and open the PR.

**Comment by aearly** [comment]
Yeah, it's 95% of the way there, it's all small tweaks from here on out. :smile: :100:

**Comment by megawac** [comment]
@hargasinski I think I fixed that issue earlier (didn't test much though as I was busy with other things) if you get a second can you confirm that https://github.com/hargasinski/async/commit/becd6835b5378d62b3fee896648b9a8f10f8ec64 fixes it

**Comment by hargasinski** [comment]
@megawac sorry, I didn't realize you fixed it. I can't test it now, but from the looks of it, it should work. I'll quickly test it again tonight before squashing the commits. Thanks for that!

**Comment by megawac** [comment]
Yeah I forgot to ping this issue when fixing it, my b

**Comment by hargasinski** [comment]
I just opened the [pull request](https://github.com/caolan/async/pull/1202) :smile:. @megawac I branched off of `docs-jsdocs` to `docs-pr` for the PR, just in case I messed something up while squashing the commits. It ended up being 18 after everything. I had to just fix one line (66a6b67), but besides that your fix worked perfectly. Thank you!
