### ISSUE TITLE
Persistent Header

### ISSUE THREAD

**Issue by megawac** [hargasinski/async#6]
Add a header which stays at the top of the document with the following details:
- Version (possibly version switcher)
- API/docs page link
- Home link
- Github (logo only?) link
- Search (#2)

For a reference, I like https://facebook.github.io/jest/docs/api.html header

/cc @hargasinski

**Comment by hargasinski** [comment]
I really like the idea! I'll prioritize it when I finish #2. It shouldn't be difficult to move the search bar to the header when it's working. In minami, there's a persistent hamburger menu to toggle the toc when the screen is too small. It should appear in the header too.

**Comment by hargasinski** [comment]
I added a prototype for this in ca0845b but it's a little bit of a mess right now. I decided to use bootstrap for it, but I realized it's a little bit of an overkill. I'll look into a better solution tomorrow.

**Comment by megawac** [comment]
done
