### ISSUE TITLE
Links to async/index

### ISSUE THREAD

**Issue by megawac** [hargasinski/async#7]
Under each main section (Collection/Util/Control Flow) we get documentation for the `index.js` file. Perhaps easiest solution would be to remove the jsdoc from `index.js`?

Also should we add a `collection.js`, `control-flow.js` and `util.js` which simply export the linked methods? Could be both useful and make documenting these sections simpler /cc @aearly

http://hargasinski.github.io/async/docs.html#controlflow

**Comment by hargasinski** [comment]
I noticed that yesterday too, I was going to add a condition `if (moduleName === 'index') return;` condition to the jsdoc plugin so that the import path doesn't get added to those. I'll wait to see what @aearly says about it.
